### ISSUE TITLE
upstream UE repo is gone

### ISSUE THREAD

**Issue by qrkourier** [ravimohan1991/LinuxUnrealTournament#1]
https://github.com/EpicGames/UnrealEngine is no longer a thing? I'm looking for the latest and greatest toward a Linux build for UT4.

**Comment by ravimohan1991** [comment]
Hi! The official UE code is up and still working. The UT Game code needs an Engine update and that is what I have been trying to achieve. I have managed to open UT4 project in UE 4.22.3 editor, but cooking the project is whole different issue. Seems like the old content is not compatible with new version of the Engine. Efforts are on, let us see where this leads to.
